### ISSUE TITLE
Bri11iant dependency security vulnerabilities

### ISSUE THREAD

**Issue by tommymchugh** [InclusiveTechNU/itl#22]
See: https://github.com/InclusiveTechNU/itl/network/alerts
Looks like there are a few dependencies that need to be updated.
Let me know if you want me to take care of it or if you can @cooperbarth.

**Comment by cooperbarth** [comment]
For reference, I've been doing all Bri11iant work in its [original repo](https://github.com/InclusiveTechNU/bri11iant) for the time being.
