### ISSUE TITLE
v11: Safe

### ISSUE THREAD

**Issue by cooperbarth** [InclusiveTechNU/itl#7]
v11 inherently exposes tools that give ease of access to any window or application being run by a computer. Implement `Safe`, a scope through which unsafe operations can be run in isolation via a callback that puts restrictions on certain actions.

**Comment by cooperbarth** [comment]
Being worked on in https://github.com/InclusiveTechNU/itl/tree/v11-safe

**Comment by tommymchugh** [comment]
Closing because we decided at this time to follow the ecmascript spec directly and not change core functionality of V8's implementation
